### PR TITLE
phase powers and currents added

### PR DESCRIPTION
**Pull request by andlem74**
web gui integration of additional arguments for json extraction of phase powers pending

### CODE REVIEW

**Comment by andlem74** [comment]
Created https://github.com/openWB/openwb-ui-settings/pull/331 for accompanying GUI addition.

**Comment by benderl** [comment]
@LKuemmel
Does load management require phase powers or currents?

**Comment by andlem74** [comment]
As I can tell from the common counter code, phase powers and currents are converted automatically if either one is available. My counter only has phase powers. Hence I implemented it. If you wish, I can add currents as well. Please let me know. Am 01.08.2023 um 08:16 schrieb benderl ***@***.***>:﻿
@LKuemmel
Does load management require phase powers or currents?

**Comment by benderl** [comment]
Thanks for also adding phase currents. Now this module seems to be complete.
@LKuemmel ?

**Review by LKuemmel — APPROVED** [review]

**Comment by fafr84** [comment]
Hi, why not implement L1, L2, L3 also, doesn't that make sense?

**Comment by benderl** [comment]
You are talking about voltages? These are not necessary. If you would like to see them on the status page, please feel free to open an new PR.

**Pull request merged**
